/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.HeadlessException;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.ImageIcon;
/**
 *
 * @author santi
 */
public class Principal extends javax.swing.JFrame {

    public JLabel[]la;
    public JLabel[]la2;
    
    public Principal() 
    {
        initComponents();
        this.setVisible(true);
        la=new JLabel[42];
        la2=new JLabel[8];
        
        
        la2[0]=this.l1;
        la2[1]=this.l2;
        la2[2]=this.l3;
        la2[3]=this.l4;
        la2[4]=this.l5;
        la2[5]=this.l6;
        la2[6]=this.l7;
        la2[7]=this.l8;
        
        la[0]=this.l9;
        la[1]=this.l10;
        la[2]=this.l11;
        la[3]=this.l12;
        la[4]=this.l13;
        la[5]=this.l14;
        la[6]=this.l15;
        la[7]=this.l16;
        la[8]=this.l17;
        la[9]=this.l18;
        la[10]=this.l19;
        la[11]=this.l20;
        la[12]=this.l21;
        la[13]=this.l22;
        la[14]=this.l23;
        la[15]=this.l24;
        la[16]=this.l25;
        la[17]=this.l26;
        la[18]=this.l27;
        la[19]=this.l28;
        la[20]=this.l29;
        la[21]=this.l30;
        la[22]=this.l31;
        la[23]=this.l32;
        la[24]=this.l33;
        la[25]=this.l34;
        la[26]=this.l35;
        la[27]=this.l36;
        la[28]=this.l37;
        la[29]=this.l38;
        la[30]=this.l39;
        la[31]=this.l40;
        la[32]=this.l41;
        la[33]=this.l42;
        la[34]=this.l43;
        la[35]=this.l44;
        la[36]=this.l45;
        la[37]=this.l46;
        la[38]=this.l47;
        la[39]=this.l48;
        la[40]=this.l49;
        la[41]=this.l50;
        
        
       
        this.setSize(1000,800);
         
        
     
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l50 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l16 = new javax.swing.JLabel();
        l17 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        l23 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l26 = new javax.swing.JLabel();
        l27 = new javax.swing.JLabel();
        l24 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        l19 = new javax.swing.JLabel();
        l37 = new javax.swing.JLabel();
        l38 = new javax.swing.JLabel();
        l39 = new javax.swing.JLabel();
        l40 = new javax.swing.JLabel();
        l41 = new javax.swing.JLabel();
        l42 = new javax.swing.JLabel();
        l43 = new javax.swing.JLabel();
        l44 = new javax.swing.JLabel();
        l45 = new javax.swing.JLabel();
        l46 = new javax.swing.JLabel();
        l47 = new javax.swing.JLabel();
        l48 = new javax.swing.JLabel();
        l49 = new javax.swing.JLabel();
        l25 = new javax.swing.JLabel();
        l31 = new javax.swing.JLabel();
        l32 = new javax.swing.JLabel();
        l30 = new javax.swing.JLabel();
        l33 = new javax.swing.JLabel();
        l36 = new javax.swing.JLabel();
        l35 = new javax.swing.JLabel();
        l34 = new javax.swing.JLabel();
        l28 = new javax.swing.JLabel();
        l29 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        l50.setForeground(new java.awt.Color(0, 0, 0));
        l50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l50.setText("50");

        l15.setForeground(new java.awt.Color(0, 0, 0));
        l15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l15.setText("15");

        l10.setForeground(new java.awt.Color(0, 0, 0));
        l10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l10.setText("10");

        l12.setForeground(new java.awt.Color(0, 0, 0));
        l12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l12.setText("12");

        l13.setForeground(new java.awt.Color(0, 0, 0));
        l13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l13.setText("13");

        l21.setForeground(new java.awt.Color(0, 0, 0));
        l21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l21.setText("21");

        l3.setForeground(new java.awt.Color(0, 0, 0));
        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-ejec-libre.png"))); // NOI18N
        l3.setText("3");

        l4.setForeground(new java.awt.Color(0, 0, 0));
        l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-ejec-libre.png"))); // NOI18N
        l4.setText("4");

        l9.setForeground(new java.awt.Color(0, 0, 0));
        l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l9.setText("9");

        l11.setForeground(new java.awt.Color(0, 0, 0));
        l11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l11.setText("11");

        l14.setForeground(new java.awt.Color(0, 0, 0));
        l14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l14.setText("14");

        l16.setForeground(new java.awt.Color(0, 0, 0));
        l16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l16.setText("16");

        l17.setForeground(new java.awt.Color(0, 0, 0));
        l17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l17.setText("17");

        l22.setForeground(new java.awt.Color(0, 0, 0));
        l22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l22.setText("22");

        l23.setForeground(new java.awt.Color(0, 0, 0));
        l23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l23.setText("23");

        l8.setForeground(new java.awt.Color(0, 0, 0));
        l8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-ejec-libre.png"))); // NOI18N
        l8.setText("8");

        l5.setForeground(new java.awt.Color(0, 0, 0));
        l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-ejec-libre.png"))); // NOI18N
        l5.setText("5");

        l18.setForeground(new java.awt.Color(0, 0, 0));
        l18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l18.setText("18");

        l2.setForeground(new java.awt.Color(0, 0, 0));
        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-ejec-libre.png"))); // NOI18N
        l2.setText("2");

        l6.setForeground(new java.awt.Color(0, 0, 0));
        l6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-ejec-libre.png"))); // NOI18N
        l6.setText("6");

        l7.setForeground(new java.awt.Color(0, 0, 0));
        l7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-ejec-libre.png"))); // NOI18N
        l7.setText("7");

        l26.setForeground(new java.awt.Color(0, 0, 0));
        l26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l26.setText("26");

        l27.setForeground(new java.awt.Color(0, 0, 0));
        l27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l27.setText("27");

        l24.setForeground(new java.awt.Color(0, 0, 0));
        l24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l24.setText("24");

        l20.setForeground(new java.awt.Color(0, 0, 0));
        l20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l20.setText("20");

        l19.setForeground(new java.awt.Color(0, 0, 0));
        l19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l19.setText("19");

        l37.setForeground(new java.awt.Color(0, 0, 0));
        l37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l37.setText("37");

        l38.setForeground(new java.awt.Color(0, 0, 0));
        l38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l38.setText("38");

        l39.setForeground(new java.awt.Color(0, 0, 0));
        l39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l39.setText("39");

        l40.setForeground(new java.awt.Color(0, 0, 0));
        l40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l40.setText("40");

        l41.setForeground(new java.awt.Color(0, 0, 0));
        l41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l41.setText("41");

        l42.setForeground(new java.awt.Color(0, 0, 0));
        l42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l42.setText("42");

        l43.setForeground(new java.awt.Color(0, 0, 0));
        l43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l43.setText("43");

        l44.setForeground(new java.awt.Color(0, 0, 0));
        l44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l44.setText("44");

        l45.setForeground(new java.awt.Color(0, 0, 0));
        l45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l45.setText("45");

        l46.setForeground(new java.awt.Color(0, 0, 0));
        l46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l46.setText("46");

        l47.setForeground(new java.awt.Color(0, 0, 0));
        l47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l47.setText("47");

        l48.setForeground(new java.awt.Color(0, 0, 0));
        l48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l48.setText("48");

        l49.setForeground(new java.awt.Color(0, 0, 0));
        l49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l49.setText("49");

        l25.setForeground(new java.awt.Color(0, 0, 0));
        l25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l25.setText("25");

        l31.setForeground(new java.awt.Color(0, 0, 0));
        l31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l31.setText("31");

        l32.setForeground(new java.awt.Color(0, 0, 0));
        l32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l32.setText("32");

        l30.setForeground(new java.awt.Color(0, 0, 0));
        l30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l30.setText("30");

        l33.setForeground(new java.awt.Color(0, 0, 0));
        l33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l33.setText("33");

        l36.setForeground(new java.awt.Color(0, 0, 0));
        l36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l36.setText("36");

        l35.setForeground(new java.awt.Color(0, 0, 0));
        l35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l35.setText("35");

        l34.setForeground(new java.awt.Color(0, 0, 0));
        l34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l34.setText("34");

        l28.setForeground(new java.awt.Color(0, 0, 0));
        l28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l28.setText("28");

        l29.setForeground(new java.awt.Color(0, 0, 0));
        l29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-econ-libre.png"))); // NOI18N
        l29.setText("29");

        l1.setForeground(new java.awt.Color(0, 0, 0));
        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/silla-ejec-libre.png"))); // NOI18N
        l1.setText("1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l1)
                            .addComponent(l5))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l9)
                                .addGap(18, 18, 18)
                                .addComponent(l10)
                                .addGap(18, 18, 18)
                                .addComponent(l11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l15)
                                .addGap(18, 18, 18)
                                .addComponent(l16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l21)
                                .addGap(18, 18, 18)
                                .addComponent(l22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l23))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l27)
                                .addGap(18, 18, 18)
                                .addComponent(l28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l29))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l33)
                                .addGap(18, 18, 18)
                                .addComponent(l34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l35))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l39)
                                .addGap(18, 18, 18)
                                .addComponent(l40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l41))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l45)
                                .addGap(18, 18, 18)
                                .addComponent(l46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l47)))
                        .addGap(80, 80, 80)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(l48)
                        .addGap(18, 18, 18)
                        .addComponent(l49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(l42)
                        .addGap(18, 18, 18)
                        .addComponent(l43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(l36)
                        .addGap(18, 18, 18)
                        .addComponent(l37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(l30)
                        .addGap(18, 18, 18)
                        .addComponent(l31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(l24)
                        .addGap(18, 18, 18)
                        .addComponent(l25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(l18)
                        .addGap(18, 18, 18)
                        .addComponent(l19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(l12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l13)
                        .addGap(18, 18, 18)
                        .addComponent(l14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l7)
                            .addComponent(l3))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l8)
                            .addComponent(l4))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1)
                    .addComponent(l3)
                    .addComponent(l4)
                    .addComponent(l2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l5)
                    .addComponent(l6)
                    .addComponent(l7)
                    .addComponent(l8))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l9)
                    .addComponent(l10)
                    .addComponent(l11)
                    .addComponent(l12)
                    .addComponent(l13)
                    .addComponent(l14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l15)
                    .addComponent(l16)
                    .addComponent(l17)
                    .addComponent(l18)
                    .addComponent(l19)
                    .addComponent(l20))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l21)
                    .addComponent(l22)
                    .addComponent(l23)
                    .addComponent(l24)
                    .addComponent(l25)
                    .addComponent(l26))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l27)
                    .addComponent(l28)
                    .addComponent(l29)
                    .addComponent(l30)
                    .addComponent(l31)
                    .addComponent(l32))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l33)
                    .addComponent(l34)
                    .addComponent(l35)
                    .addComponent(l36)
                    .addComponent(l37)
                    .addComponent(l38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l39)
                    .addComponent(l40)
                    .addComponent(l41)
                    .addComponent(l42)
                    .addComponent(l43)
                    .addComponent(l44))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l45)
                    .addComponent(l46)
                    .addComponent(l47)
                    .addComponent(l48)
                    .addComponent(l49)
                    .addComponent(l50))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(290, 0, 430, 590);

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/avion.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1040, 590);

        jButton1.setText("Registrar Usuario");

        jButton2.setText("Eliminar Usuario");

        jButton3.setText("Calcular porcentaje");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(50, 610, 950, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JLabel l1;
    public javax.swing.JLabel l10;
    public javax.swing.JLabel l11;
    public javax.swing.JLabel l12;
    public javax.swing.JLabel l13;
    public javax.swing.JLabel l14;
    public javax.swing.JLabel l15;
    public javax.swing.JLabel l16;
    public javax.swing.JLabel l17;
    public javax.swing.JLabel l18;
    public javax.swing.JLabel l19;
    public javax.swing.JLabel l2;
    public javax.swing.JLabel l20;
    public javax.swing.JLabel l21;
    public javax.swing.JLabel l22;
    public javax.swing.JLabel l23;
    public javax.swing.JLabel l24;
    public javax.swing.JLabel l25;
    public javax.swing.JLabel l26;
    public javax.swing.JLabel l27;
    public javax.swing.JLabel l28;
    public javax.swing.JLabel l29;
    public javax.swing.JLabel l3;
    public javax.swing.JLabel l30;
    public javax.swing.JLabel l31;
    public javax.swing.JLabel l32;
    public javax.swing.JLabel l33;
    public javax.swing.JLabel l34;
    public javax.swing.JLabel l35;
    public javax.swing.JLabel l36;
    public javax.swing.JLabel l37;
    public javax.swing.JLabel l38;
    public javax.swing.JLabel l39;
    public javax.swing.JLabel l4;
    public javax.swing.JLabel l40;
    public javax.swing.JLabel l41;
    public javax.swing.JLabel l42;
    public javax.swing.JLabel l43;
    public javax.swing.JLabel l44;
    public javax.swing.JLabel l45;
    public javax.swing.JLabel l46;
    public javax.swing.JLabel l47;
    public javax.swing.JLabel l48;
    public javax.swing.JLabel l49;
    public javax.swing.JLabel l5;
    public javax.swing.JLabel l50;
    public javax.swing.JLabel l6;
    public javax.swing.JLabel l7;
    public javax.swing.JLabel l8;
    public javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
